### ISSUE TITLE
replace app/queue system

### ISSUE THREAD

**Issue by evaletolab** [karibou-ch/karibou-api#12]
1) system System notifications testing of simple queue with http.request:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at Queue.await (test/system.js:203:20)
      at Timeout._onTimeout (app/queue.js:72:25)

**Comment by evaletolab** [comment]
* https://hashnode.com/post/10-things-you-shouldnt-do-while-running-nodejs-in-production-cisab2fyu0s9oth5341faywcw
* https://blog.risingstack.com/node-js-security-checklist/ qui propose d'utiliser https://www.npmjs.com/package/ratelimiter
